# -*- coding: utf-8 -*-
"""SOM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uoI519sA4qLn_DHAVv6Nv6cYxR4dOwQR
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset=pd.read_csv('/content/Credit_Card_Applications.csv')

X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,-1].values

"""Feature Scaling"""

from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler(feature_range=(0,1))
X=sc.fit_transform(X)

!pip install minisom
from minisom import MiniSom
som=MiniSom(x=10,y=10,input_len=15,sigma=1.0,learning_rate=0.4)
som.random_weights_init(X)
som.train_random(data=X,num_iteration=100)

from pylab import bone,pcolor,colorbar,plot,show
bone()
pcolor(som.distance_map().T)
colorbar()
markers=['x','s']
colors=['r','g']
for i,x in enumerate(X):
  w= som.winner(x)
  plot(w[0]+0.5,
       w[1]+0.5,
       markers[Y[i]],
       markeredgecolor=colors[Y[i]],
       markerfacecolor='None',
       markersize=7,
       markeredgewidth=2)
show()

"""Finding Frauds"""

mappings=som.win_map(X)
#Enter the coordinates of white boxes and concatenate each results.
frauds=np.concatenate((mappings[(1,1)],mappings[(7,3)],mappings[(1,8)]), axis=0)

frauds=sc.inverse_transform(frauds)

print("These are potential fraud customers:")
for i in frauds:
  print(i[0])

